name: Selenium NUnit Tests
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Install Chrome
        uses: browser-actions/setup-chrome@latest

      - name: Restore dependencies
        run: dotnet restore

      # Ejecutar solo un método específico
      - name: Run FirstTestCase
        run: dotnet test --filter FullyQualifiedName~AutomatedScript.Tests.AmazonTestCases.FirstTestCase
